[package]
name = "orion-syspec"
version = "0.1.0"
edition = "2024"

[dependencies]
orion-error =  "0.2"
#orion-error= {path = "../orion-error/"}
orion-exchange = {path = "../orion-exchange/"}
anyhow = "~1.0"
comfy-table = "~7.1"
contracts = "~0.6"
env_logger = "~0.11"
reqwest = "~0.12"
async-trait = "0.1"
log = "~0.4"
serde = "~1.0"
serde_derive = "~1.0"
serde_json = "~1.0"
serde_ini = "0.2.0"
strfmt = "~0.2"
tokio = { version = "1.45", features = ["full"] }
tracing = "0.1"
thiserror = "~1.0"
toml = "~0.7"
walkdir = "~2.5"
delegate = "0.13.3"
wildmatch = "~2.4"
lazy_static = "~1.5"
futures = "0.3"

handlebars = "6.3"
fs_extra = "1.3"
regex = "1.10"
derive-getters = "0.5.0"
git2 = "0.20"
derive_more = { version = "2.0", features = ["full"] }

[dev-dependencies]
mockall = "~0.11"
httpmock = "0.7.0"
criterion = "0.5.1"
tempfile = "3.3"
