[package]
name = "galaxy-ops"
version = "1.1.1" # @gxl:set(version)
edition = "2024"
license = "Apache-2.0"

[[bin]]
name = "gops"
path = "app/gops/main.rs"

[workspace]
members = ["."]

[workspace.dependencies]
anyhow = "1.0"
async-trait = "0.1"
clap = { version = "4.5", features = ["derive"] }
contracts = "~0.6"
derive-getters = "0.5.0"
derive_more = { version = "2.0", features = ["full"] }
dialoguer = "~0.12"
env_logger = "~0.11"
flate2 = "~1.1"
fs_extra = "1.3"
getset = "0.1.6"
git2 = "0.20"
handlebars = "6.3"
home = "0.5"
indexmap = { version = "2.10", features = ["serde"] }
indicatif = "0.18"
log = "0.4"
orion-error = "0.6"
orion-infra = "0.5"
orion_conf = { version = "0.5", features = ["full"] }
orion_variate = { package = "orion-accessor", version = "0.6" }
orion_vars = { package = "orion-variate", version = "0.11" }
os_info = "3"
reqwest = { version = "0.12", features = ["multipart"] }
scopeguard = "1.2.0"
serde = "1.0"
serde_derive = "1.0"
serde_ini = "0.2.0"
serde_json = "1.0"
serde_yaml = "0.9"
flexi_logger = "~0.31"
tar = "0.4"
thiserror = "2.0"
tokio = { version = "1.47", features = ["full"] }
toml = "1.0"
tracing = "0.1"
url = "2.5"

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
bytes = "1.0"
chrono = "0.4"
clap = { workspace = true }
contracts = { workspace = true }
derive-getters = { workspace = true }
derive_more = { workspace = true }
dialoguer = { workspace = true }
env_logger = { workspace = true }
flate2 = { workspace = true }
fs_extra = { workspace = true }
getset = { workspace = true }
git2 = { workspace = true }
glob = "0.3"
handlebars = { workspace = true }
home = { workspace = true }
indicatif = { workspace = true }
indexmap = { workspace = true }
log = { workspace = true }
once_cell = "1.19"
orion-error = { workspace = true }
orion-infra = { workspace = true }
orion_conf = { workspace = true }
orion_variate = { workspace = true }
orion_vars = { workspace = true }
os_info = { workspace = true }
pathdiff = "0.2.3"
regex = "1.10"
reqwest = { workspace = true }
scopeguard = { workspace = true }
serde = { workspace = true }
serde_derive = { workspace = true }
serde_ini = { workspace = true }
serde_json = { workspace = true }
serde_yaml = { workspace = true }
tar = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tokio-util = { version = "0.7", features = ["codec"] }
toml = { workspace = true }
tracing = { workspace = true }
url = { workspace = true }
walkdir = "~2.5"
wildmatch = "~2.4"

[dev-dependencies]
criterion = "~0.7"
mockall = "~0.13"
mockito = "1.7"
tempfile = "3.3"
