version = "1.0"

[[files]]
path = "./conf/dvron.toml"

[[files]]
path = "./conf/dvadm.oml"

[[files]]
path = "./conf/knowdb.toml"

[[files]]
path = "./sink/framework.toml"

[[files]]
path = "./sink/privacy.toml"

[[files]]
path = "./source/dysrc.toml"
